version: '3.1'
services:
  database:
    image: "postgres"
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
  
#   backend:
#     build: /backend
#     ports:
#       - "8080:3001"
#     links:
#       - database
#     restart: always

#  frontend:
#    build: /my-app
#    ports:
#      - "8080:3000"
#    restart: always