version: "3.1"
services:
  database:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567
      - POSTGRES_DB=vavjs3
    ports:
      - 5432:5432

  backend:
    build: ./vavjs3_be
    ports:
      - "5000:5000"
    env_file:
      - .env
    links:
      - database
    restart: always
    depends_on:
      - database

  frontend:
    build: ./vavjs3_fe
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - backend
